### ISSUE TITLE
ubuntu 20.04 设置静态ip

### ISSUE THREAD

**Issue by vuuvv** [vuuvv/blog#18]
### 编辑/etc/netplan/00-installer-config.yaml文件为：

```yaml
network:
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
        - 192.168.137.110/24
      gateway4: 192.168.137.1
      nameservers:
        addresses: [114.114.114.114]
  version: 2
```

### 执行

```sh
 sudo netplan apply
```

### 查看

```sh
ip addr
```
